import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Music.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Music</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Music</h1>
        <p>This page is under construction! Come back later.</p>
      </main>
    </>
  )
}
