import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Music.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Music</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.hero}>
          <h1>Music</h1>
        </section>
        <section className={styles.content}>
          <p>You can find my work with Amienus on Discogs!</p>
          <a className={styles.btn_discogs} href="https://www.discogs.com/artist/3429641-Zack-Morgenthaler">
            <Image src="/img/discogs-logo.svg" width={64} height={32} />
          </a>
        </section>
        <section>
          <h2>Soundcloud</h2>
          <a className="btn" href="https://soundcloud.com/zack-morgenthaler-505021258">
            <Image className="social-icon" src="/img/icon-soundcloud.svg" width={365} height={365} alt="Soundcloud Logo" />
          </a>
        </section>
        <section>
          <h2>Metal Bands</h2>
          <ul>
            <li>
              <a href="https://facebook.com/Amiensus">
                Amiensus
              </a>
            </li>
            <li>
              <a href="https://facebook.com/phantasmora">
                Phantasmora
              </a>
            </li>
          </ul>
        </section>
      </main>
    </>
  )
}
